### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by mugishasam123** [tariktesfa/Leaderboard#3]
hey, @tariktesfa ✋  congratulations on the work you did so far 🎉🎉

but there are some issues to work on to continue with the next project 

- please you can consider removing the script source in index.html in the src folder because webpack does it automatically
- please consider making arguments as variables, not code lines like https://github.com/tariktesfa/Leaderboard/blob/04b5ffb1cdb1b18524d36a73cbe736565c4e0ce2/src/index.js#L10
- please consider shortening these code lines in one code of just `Leaderboard.load`  https://github.com/tariktesfa/Leaderboard/blob/04b5ffb1cdb1b18524d36a73cbe736565c4e0ce2/src/index.js#L4-L6

hope to hear from you when issues are solved ❤️

**Comment by tariktesfa** [comment]
Thanks for the issue. I have resolved them all.
