### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by VSeray** [tariktesfa/Leaderboard#5]
Hello @tariktesfa 👋,

Your project looks great, but there are some suggestions that we would like to give to make your project more professional.

- It would be better if you could add validation to your name input to accept only text and no numbers.[Code line](https://github.com/tariktesfa/Leaderboard/blob/df5f621f7052da6eb6e7848844b234465afb70b0/src/index.html#L26)
- [Optional] Get and post could be in different scripts.
- It would be better if your MIT License works.

Great Job 🥳 🍾

**Comment by tariktesfa** [comment]
Thanks for the feedback.
